version: "3.9"

services:
  configserver:
    image: "eazybytes/configserver:s8"
    container_name: configserver-ms
    ports:
      - "9071:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  eurekaserver:
    image: "eazybytes/eurekaserver:s8"
    container_name: eurekaserver-ms
    ports:
      - "8077:8070"
    healthcheck:
      test: "curl --fail --silent http://localhost:8070/actuator/health/readiness | grep UP || exit"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service:  microservice-configserver-config
    environment:
      SPRING_APPLICATION_NAME: "eurekaserver"

  accounts:
    image: "eazybytes/accounts:s8"
    container_name: accounts-ms
    ports:
      - "8089:8080"
    environment:
      SPRING_APPLICATION_NAME: "accounts"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans:
    image: "eazybytes/loans:s8"
    container_name: loans-ms
    ports:
      - "8099:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans"
      EUREKA_INSTANCE_INSTANCE_ID: "loans-ms:${SAMPLE}"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans1:
    image: "eazybytes/loans:s8"
    container_name: loans1-ms
    ports:
      - "8999:8090"
    environment:
      SPRING_APPLICATION_NAME: "loans1"
      EUREKA_INSTANCE_INSTANCE_ID: "loans1-ms:${SAMPLELoan}"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: "eazybytes/cards:s8"
    container_name: cards-ms
    ports:
      - "9009:9000"
    environment:
      SPRING_APPLICATION_NAME: "cards"
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  eazybank:
    driver: "bridge"